apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: stage
  name: cart-abandonment
  labels:
    app: cart-abandonment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart-abandonment
  template:
    metadata:
      name: cart-abandonment
      labels:
        app: cart-abandonment
    spec:
      containers:
      - name: cart-abandonment
        image: pyrite.azurecr.io/cart-abandonment-service:latest
        imagePullPolicy: IfNotPresent
      serviceAccount: pyrite
      serviceAccountName: pyrite
