apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: stage
  name: cart-abandonment
  labels:
    app: cart-abandonment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart-abandonment
  template:
    metadata:
      name: cart-abandonment
      labels:
        app: cart-abandonment
    spec:
      containers:
      - name: cart-abandonment
        image: pyrite.azurecr.io/cart-abandonment-service@sha256:0efbeca5a1236173a6fa5f937fc65057e94e019c18292fc9b3c8d2eb665ddd42
        imagePullPolicy: Always
        ports:
        - containerPort: 9876
          name: http
      serviceAccount: pyrite
      serviceAccountName: pyrite
