apiVersion: kubeless.io/v1beta1
kind: Function
metadata:
  clusterName: ""
  creationTimestamp: 2018-12-04T17:51:44Z
  finalizers:
  - kubeless.io/function
  generation: 1
  labels: {}
  name: process-abandoned-cart
  namespace: stage
  resourceVersion: "3173379"
  selfLink: /apis/kubeless.io/v1beta1/namespaces/stage/functions/process-abandoned-cart
  uid: 437ce517-f7ed-11e8-8c9b-42010a9c0042
spec:
  checksum: sha256:9216b3cea780f7fd9ac94464ce48e00a6c3d793432273522d362fd23d8bbe1f1
  deployment:
    metadata:
      creationTimestamp: null
    spec:
      strategy: {}
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - name: ""
            resources: {}
    status: {}
  deps: ""
  function: |-
    module.exports = { main: function (event, context) {
      console.log(event);
    } }
  function-content-type: text
  handler: handler.main
  horizontalPodAutoscaler:
    metadata:
      creationTimestamp: null
    spec:
      maxReplicas: 0
      scaleTargetRef:
        kind: ""
        name: ""
    status:
      conditions: null
      currentMetrics: null
      currentReplicas: 0
      desiredReplicas: 0
  runtime: nodejs8
  service:
    ports:
    - name: http-function-port
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      created-by: kubeless
      function: process-abandoned-cart
  timeout: ""
  topic: undefined
