apiVersion: v1
kind: Service
metadata:
  name: cart-visual
  labels:
    example: cart-visual
  annotations:
    auth.istio.io/80: NONE
spec:
  ports:
  - name: http
    port: 80
  selector:
    example: cart-visual
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cart-visual
spec:
  replicas: 1
  template:
    metadata:
      labels:
        example: cart-visual
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      # replace the repository URL with your own repository (e.g. {DockerID}/http-db-service:0.0.x for Docker Hub).
      - image: pyrite.azurecr.io/cart-visual
        imagePullPolicy: Always
        name: cart-visual
        ports:
        - name: http
          containerPort: 80
        resources:
          limits:
            memory: 100Mi
          requests:
            memory: 32Mi
      serviceAccount: pyrite
      serviceAccountName: pyrite
