apiVersion: kubeless.io/v1beta1
kind: Function
metadata:
  clusterName: ""
  creationTimestamp: 2018-12-04T16:27:57Z
  finalizers:
  - kubeless.io/function
  generation: 1
  labels: {}
  name: event-ingress
  namespace: stage
  resourceVersion: "3162696"
  selfLink: /apis/kubeless.io/v1beta1/namespaces/stage/functions/event-ingress
  uid: 8eeb63b0-f7e1-11e8-8c9b-42010a9c0042
spec:
  checksum: sha256:7212b80d89dabf665eae3afc95344c5025e0a18d16abf307ec06a8f86318daa0
  deployment:
    metadata:
      creationTimestamp: null
    spec:
      strategy: {}
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - name: ""
            resources: {}
    status: {}
  deps: |-
    {
      "name": "app",
      "version": "0.0.1",
      "dependencies": {
        "request": "^2.85.0"
      }
    }
  function: |-
    const request = require('request');

    module.exports = { main: function (event, context) {
    console.log("Team Pyrite [" + event.data + "] received event [" + event.data +"]"); //test

        url = "http://cart-abandonment.stage/events";
        console.log("Processing event");
        console.log(event);

        request.post({
            url: url,
            json: event
        }, function (error, response, body) {
            if (error === null) {
                console.log(body);
            } else {
                console.log("error: " + error);
            }
        });
    } }
  function-content-type: text
  handler: handler.main
  horizontalPodAutoscaler:
    metadata:
      creationTimestamp: null
    spec:
      maxReplicas: 0
      scaleTargetRef:
        kind: ""
        name: ""
    status:
      conditions: null
      currentMetrics: null
      currentReplicas: 0
      desiredReplicas: 0
  runtime: nodejs8
  service:
    ports:
    - name: http-function-port
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      created-by: kubeless
      function: event-ingress
  timeout: ""
  topic: http
